source 'https://api.berkshelf.com'
###
cookbook 'cacert'
cookbook 'cron'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'hostname'
cookbook 'logwatch'
cookbook 'monit'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'openssl'
cookbook 'ssl_certificate'
cookbook 'sudo'
cookbook 'user'
cookbook 'mongodb'
